Make unregisterall() remove UserDefaults + Make it a public method
sindresorhus/KeyboardShortcuts pull request #184
Opened 2024-09-21 04:34 UTC by stormychel

- unregisterall() now also removes UserDefaults entries
- made unregisterall() public since it can be useful to clean up all shortcuts from an app

2024-09-22 18:33 UTC, sindresorhus commented
I'm not sure it makes sense to expose this anymore. The recommended API is with `.events()` and it automatically unregisters when it's no longer listening to events.

2024-09-22 18:35 UTC, stormychel commented
We have some stuck hotkeys in our app that could benefit from this, but we could off course use a custom branch to deal with it,, whatever works best for you.
Thanks for making this available!

2024-09-24 05:12 UTC, stormychel commented
Do you want me to split up the PR so only "unregisterall() now also removes UserDefaults entries" can get merged?
It is a TODO in your code...

2024-09-25 18:00 UTC, sindresorhus commented
I think it makes more sense if it's called `resetAll()`. I got confused by its use-case because of its name. I assume you need this to **reset** all the shortcuts?

I'm ok with exposing it then. But it will need doc comments. And it should probably be moved to below `public static func reset(_ names: Name...) {`.

2024-09-25 19:17 UTC, stormychel commented
It depends whether you think this is useful for others. We are already on a custom branch, and also have a method "public static func unregisterUnknownShortcuts(knownShortcutNames: [KeyboardShortcuts.Name]) {
}" which removes shortcuts unknown by the app so maybe our needs are a bit more than what others would typically need so I don't know whether these are useful for everyone. Will make the changes you requested + doc comments, thanks for reviewing!

2024-09-25 20:44 UTC, sindresorhus commented
> static func unregisterUnknownShortcuts(knownShortcutNames: [KeyboardShortcuts.Name]) {

This one is indeed too niche.

2024-09-27 05:17 UTC, stormychel commented
> > static func unregisterUnknownShortcuts(knownShortcutNames: [KeyboardShortcuts.Name]) {
> 
> This one is indeed too niche.

Totally agree :)

I will clean up my PR and add docs over the weekend.

@sindresorhus if we have a shortcut that is stuck, even after doing our unregisterUnknownShortcuts() thing, is there anything we can do to get rid of it without wiping user defaults for app completely? One of our Macs has a shortcut that is stuck this way, hence our efforts to create unregisterUnknownShortcuts(), but even this does not solve it, while the method definitely works. This is only on one development machine, I am 100% sure this is from testing work branches, and tbh I'd just clear defaults at this point, but we want to make sure this does not happen to users. Any ideas on how this could happen?

2024-10-05 07:46 UTC, stormychel commented
@sindresorhus added docs & relocated method: https://github.com/sindresorhus/KeyboardShortcuts/pull/184/commits/5dda3b423b950d49b0a1ce4d1d939a7494a19a89

2024-10-05 15:43 UTC, sindresorhus commented
> I think it makes more sense if it's called resetAll().

2024-10-06 02:36 UTC, stormychel commented
> > I think it makes more sense if it's called resetAll().

Yes, I forgot, my bad, done now: https://github.com/sindresorhus/KeyboardShortcuts/pull/184/commits/0af13cf54c2ee953d0e71b5b4ed6b4a0afcaace8

2024-10-09 06:33 UTC, sindresorhus requested changes

2024-10-09 06:33 UTC, sindresorhus commented on Sources/KeyboardShortcuts/KeyboardShortcuts.swift
> +	Use this method to completely reset the state of all keyboard shortcuts in your app, including removing any saved user-defined shortcuts and default shortcuts.
These 3 paragraphs pretty much say the same thing.

2024-10-09 06:33 UTC, sindresorhus commented on Sources/KeyboardShortcuts/KeyboardShortcuts.swift
> +	- Note: This action cannot be undone. All shortcuts will be removed, including any default shortcuts defined in `Name`. If you want to reset shortcuts back to their default values, consider using `.
> If you want to reset shortcuts back to their default values, consider using `.reset(_:)` instead.

I don't think it makes sense that this has different behavior than `.reset()`. `resetAll` should just be `reset` for **all**.

2024-10-09 06:33 UTC, sindresorhus commented
You have some lint violations. See the diff.

2024-10-09 06:37 UTC, stormychel commented
Nevermind, I will just keep on using my forked version, got other stuff to do than endlessly working on one simple PR.
Thanks for considering though!

2024-10-09 06:37 UTC, closed without merging